language: go

go:
  - 1.8
  - 1.9

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/golang/lint/golint
  - dep ensure

script:
  - golint . parser
  - go test ./parser -v
