[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"
[[constraint]]
  branch = "master"
  name = "github.com/orcaman/concurrent-map"
